import { getDb } from '@/lib/mongodb';
import { v4 as uuidv4 } from 'uuid';

const COLLECTION_NAME = 'transactions';

async function getCollection() {
  const db = await getDb();
  return db.collection(COLLECTION_NAME);
}

/**
 * Ensure database indexes for transactions collection
 * Requirements: 8.4-8.6
 */
export async function ensureIndexes() {
  const collection = await getCollection();
  
  // Unique index on id field
  await collection.createIndex({ id: 1 }, { unique: true });
  
  // Single field indexes
  await collection.createIndex({ date: -1 });
  await collection.createIndex({ templateId: 1 });
  await collection.createIndex({ isPending: 1 });
  
  // Compound index for efficient querying of template transactions by date
  await collection.createIndex({ templateId: 1, date: 1 });
}

export async function createTransaction(transaction) {
  const collection = await getCollection();
  
  const newTransaction = {
    id: uuidv4(),
    ...transaction,
    isAutoGenerated: transaction.isAutoGenerated || false,
    templateId: transaction.templateId || null,
    isPending: transaction.isPending || false,
    createdAt: new Date(),
    updatedAt: new Date()
  };
  
  await collection.insertOne(newTransaction);
  return newTransaction;
}

export async function getTransactions(filter = {}) {
  const collection = await getCollection();
  const transactions = await collection
    .find(filter)
    .sort({ date: -1 })
    .toArray();
  return transactions;
}

export async function getTransactionById(id) {
  const collection = await getCollection();
  return await collection.findOne({ id });
}

export async function updateTransaction(id, updates) {
  const collection = await getCollection();
  
  const result = await collection.findOneAndUpdate(
    { id },
    { 
      $set: { 
        ...updates, 
        updatedAt: new Date() 
      } 
    },
    { returnDocument: 'after' }
  );
  
  return result;
}

export async function deleteTransaction(id) {
  const collection = await getCollection();
  const result = await collection.deleteOne({ id });
  return result.deletedCount > 0;
}

export async function getTransactionsByDateRange(startDate, endDate) {
  const collection = await getCollection();
  return await collection
    .find({
      date: {
        $gte: startDate,
        $lte: endDate
      }
    })
    .sort({ date: -1 })
    .toArray();
}
